name: Publish
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com
          scope: '@andreascaldewei'

      - name: npm run publish
        run: npm install @angular/cli -g

      - name: npm run publish
        run: npm run publish




      - name: npm run publish
        run: |
          cd ./dist/angular-layout-directives-lib
          npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}
