name: Publish
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com
          scope: '@AndreasCaldewei'

      - name: install angular cli
        run: npm install @angular/cli -g

      - name: npm run publish
        run: npm run publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
